/* 
 * csim.h - Prototypes for csim.c helper function
 */

#ifndef CACHE_SIMILATOR_H
#define CACHE_SIMILATOR_H

/*
 * Represent one cache line in cache 
 */
typedef struct cache_line{
    int valid;               // valid bit for cache line
    int tag;                 // tag symbol 
    int lru_counter;         // for LRU replace policy
    int* block;              // block area for cache line
} cache_line;


/**
 * rep invariant: valid = 0 or 1, 0 < tag < 2^(address_length - s - b),
 * lru_counter >= 0, 0 < block.length < 2^b
 * abstraction function: represent one cache line 
 * safety from exposure: 
 * all fields are static, that means only can access the field in this file.
 */

/**
 * check rep_invariant 
 */
// static void check_Rep(cache_line* cache, int S, int B);


/**
 * Allocate B blocks in each cache line
 * @param cache target cache
 * @param S sets numbers
 * @param E each set have E lines
 * @param B each cache init with B blocks
 */
void init_cache_blocks(cache_line** cache, int S, int E, int B);


/**
 * access cache by inputing memory address, and memory address divided into three parts,
 * S, tag, block_offset. if access success, return 1. otherwise return 0.
 * @param cache target cache is 2D array of cache_line object
 * @param E each set havs E lines
 * @param address unsigned main memory address
 * @param b lower b bits to represent block offset
 * @param s higher than b, s bits to represent set number
 * @param time global timer variable counter memory assess number for lru algorithm
 * @return if this memory value already exited in cache(hit), return 1. otherwise(miss) if occur ecviction return -1, else return 0.
 */
int cache_access(cache_line** cache, unsigned long long address, int E, int b, int s, unsigned time);


/**
 * if cache missed, insert memory address's value to cache, 
 * and set up responding arguments
 * @param set_index insert target set number in cache(0 < S < cache.length)
 * @param E insert line number of set(0 < E < cache[0].length)
 * @param cache insert target cache
 * @param target_tag target memory address tag symbol
 * @param time global timer variable counter memory assess number for lru algorithm
 * @return insert with eviction return -1, insert without eviction return 0.
 */
int cache_insert(cache_line** cache, int set_index, int E, int target_tag, unsigned time);


/**
 * least-recently used replacement policy implemention for choosing cache line to evict
 * @param cache target cache
 * @param s target set number for replace new main address value(0 < S < cache.length)
 *  @param E insert line number of set(0 < E < cache[0].length)
 * @return return replacement index in cache if success, otherwise return 0.
 */
int LRU(cache_line** cache, int s, int E);


/**
 * Get main memory address' tag number which is used in cache
 * @param address unsigned long long hex number of main memory address 
 * @param b lower b bits to represent block offset
 * @param s higher than b, s bits to represent set number
 * @return tag symbol for cache 
 */
unsigned get_address_tag(unsigned long long address, int b, int s);


/**
 * Get main memory address' set number which is used in cache
 * @param address unsigned long long hex number of main memory address 
 * @param b lower b bits to represent block offset
 * @param s higher than b, s bits to represent set number
 * @return set number for cache 
 */
unsigned get_address_set(unsigned long long address, int b, int s);


/**
 * Get main memory address' block offset number which is used in cache
 * @param address unsigned long long hex number of main memory address 
 * @param b lower b bits to represent block offset
 * @param s higher than b, s bits to represent set number
 * @return block offset for cache
 */
unsigned get_address_block_offset(unsigned long long address, int b, int s);


/**
 * According to cache_flag, modify cache state for hits, misses, eviction
 * @param cache_flag generated by cache_access function, cache_flag = 1, -1, or 0
 * @param hits int* pointer, target hits variable address
 * @param misses int* pointer, misses variable address
 * @param eviction int* pointer, eviction variable address
 */
void modify_cache_state(int cache_flag, int* hits, int* misses, int* eviction);


/**
 * Free all blocks memory in cache
 */
void free_cache_blocks(cache_line** cache, int S, int E);

#endif /* CACHE_SIMILATOR_H  */

